#!/bin/bash

for file in $(git diff --cached --name-only | grep -E '\.(js|jsx)$')
do
  node_modules/.bin/eslint "$file" --fix # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0  ]; then
    echo "ESLint failed on staged file '$file'. Please check your code and try again. You can run ESLint manually via npm run lint."
    exit 1 # exit with failure status
  fi
done

node_modules/.bin/jest
